### ISSUE TITLE
Spam: 'void' method 'getBody' result used

### ISSUE THREAD

**Issue by Pascalmh** [webSPELL/webSPELL#141]
Name      
spam.php    

Location      
file .../src/func/spam.php - [webSPELL-4.2.3]    

Problem synopsis      
'void' method 'getBody' result used (at line 182)

**Comment by Pascalmh** [comment]
Name      modrewrite.php    
Location      file .../admin/modrewrite.php - [webSPELL-4.2.3]    
Problem synopsis      'void' function 'var_dump' result used (at line 335)

**Comment by derchrisuk** [comment]
I believe this is obsolete now and can be closed?

**Comment by Pascalmh** [comment]
@Phhere I guess you fixed it, right?

**Comment by Phhere** [comment]
fixed
