### ISSUE TITLE
"Go to last post"

### ISSUE THREAD

**Issue by Siinex** [webSPELL/webSPELL#189]
Hey there,

I'm not quite sure whether or not to write in English or German, so I'll just do both. Until now you could click a forum topic to open it or you can choose a site via the multisite icon, but wouldn't it be more favorable to jump to the latest post or even better to the user's last unseen post?

Hidiho,

bisher kann man ja "nur" entweder in die Topic rein, über den Topiclink, oder auf eine gewünschte Seite springen. Aber cool wär's doch, wenn man zum aktuellsten Post gehen kann oder noch besser zum zuletzt ungelesenen.

~
Siinex

**Comment by Pascalmh** [comment]
Thank you for your Feedback. We try to stick to English here as much as possible.
I think we will discuss this on Tuesday (https://plus.google.com/u/0/events/c13n9kuhfi3kn745r3o64rblrqc) as we are having a "feature stop" for webSPELL 4.3 and this seems to be in the grey area between a feature and an enhancement.

**Comment by Siinex** [comment]
Okay, no problem. I think especially the forum has much room for.. enhancements. :D

**Comment by derchrisuk** [comment]
We discussed this during our last meetings, and we believe we would introduce a performance bottleneck on the system if we would implement it.
We are still not sure if and how this could be done, at least not with the current codebase.

**Comment by derchrisuk** [comment]
Not implementable with current codebase.
