### ISSUE TITLE
register - required fields

### ISSUE THREAD

**Issue by xxxrenegade** [webSPELL/webSPELL#202]
Bei der Registrierung sollte man auf jedenfall noch die beiden Pflichtfelder Vorname und Geburtstag einfügen. 

Viellicht auch noch Felder die keine Pflichtfelder sind wie z.B. Vorname, Land, Geschlecht und Homepage.

Man könnte auch darüber nachdenken ob man nicht Geschlecht und die Angabe des Lands zu Pflichtfeldern macht.

https://www.webspell.org/index.php?site=forum_topic&topic=43222&type=ASC&page=1

**Comment by Pascalmh** [comment]
Weitere Pflichtfelder würde ich nicht hinzufügen, jedes weitere Feld das vom Benutzer ausgefüllt werden muss macht die Wahrscheinlichkeit einer Registrierung unwahrscheinliche. Gerade wenn man mit dem Handy unterwegs ist freut man sich über kurze Formulare. Werden das morgen im Hangout nochmal besprechen.

**Comment by derchrisuk** [comment]
From my point of view, there should be only 3-4 required fields for registration:

username, email, password, verify password.

Anything else, if required, should be recorded after the initial registration.
