### ISSUE TITLE
BBcodes get ignored in top-news

### ISSUE THREAD

**Issue by DDaems** [webSPELL/webSPELL#211]
If you use BBcode at the start of your newspost. 
Either for a different color or something else.

The BBcode gets pasted in plane text at the top-news description line.
After i noticed that, i was wondering if you could actually use BBcode in your title name too.
But apperently not, maybe this could be cool to include?

edit:
After giving this a bit of though, i think BBcodes should be stripped out of the top-news widget by default.

**Comment by derchrisuk** [comment]
Works as designed

**Comment by DDaems** [comment]
I can't imagine this is supposed to happen, so i added a picture to clarify the problem a bit more.

![top-news](https://cloud.githubusercontent.com/assets/7575436/6658769/63a1dd06-cb74-11e4-9abf-58d8770bd2a2.jpg)

**Comment by DDaems** [comment]
Uch i didn't know github tracked all my commits, even when i didn't ask for a pullrequest and deleted the repository afterwards.

Anyway, i first added the fix directly to the dev without branching, than i started over again and branched of master. But after that i decided to do it again, and just branch of dev. Sinds i though this was more logical. Sorry for all the references.
