### ISSUE TITLE
Password Hash Bug by user id 1

### ISSUE THREAD

**Issue by xxxrenegade** [webSPELL/webSPELL#213]
Bei einer neu Installation vom aktuellem dev Branche ist mir aufgefallen das man sich mit dem user mit der id 1 nicht einloggen kann.

**Comment by derchrisuk** [comment]
That is already fixed since several months.
You should update your repo.

**Comment by xxxrenegade** [comment]
Ist gerade frisch aufgesetzt, der fehler scheint mit dem ajax login wieder vorhanden zu sein.

**Comment by derchrisuk** [comment]
I tested myself, and are able to login with the provided password.
