### ISSUE TITLE
Use ISO 639-1 for language files

### ISSUE THREAD

**Issue by derchrisuk** [webSPELL/webSPELL#216]
Currently we use the TLD of the country as a handle for the language.
Which is not the correct way.
For example, we use UK for English, but UK is Ukrainian

We should use the [ISO 639-1](http://en.wikipedia.org/wiki/List_of_ISO_639-1_codes)
There are only 35 translated languages at the moment, so is not a big deal.

But we need to do this for all other countries/languages at some point.

**Comment by Pascalmh** [comment]
> and optionally the region (in ISO 3166-1 Alpha 2 format)
* de: German content, independent of region
* en-GB: English content, for GB users
* de-ES: German content, for users in Spain

https://support.google.com/webmasters/answer/189077

**Comment by derchrisuk** [comment]
I already use that.
This is the current structure for our 35 languages

`af  ar_SA  bg  bs  cs  da  de  el  en  es-ES  et  fa  fi  fr  hr  hu  it  ka  lb  lt  lv  mk  nl  no  pl  pt-PT  ro  ru  sk  sl  sq  sr  sv-SE  tr  uk`
