### ISSUE TITLE
Compare passwords in length-constant time (checklogin.php)

### ISSUE THREAD

**Issue by JHGitty** [webSPELL/webSPELL#237]
The passwords on login should be checked in length-constant time to avoid time-based attacks.

```
// Compares two strings $a and $b in length-constant time.
function slow_equals($a, $b)
{
    $diff = strlen($a) ^ strlen($b);
    for($i = 0; $i < strlen($a) && $i < strlen($b); $i++)
    {
        $diff |= ord($a[$i]) ^ ord($b[$i]);
    }
    return $diff === 0;
}
```
Info/Source: http://stackoverflow.com/questions/18810431/what-that-mean-compare-two-strings-a-and-b-in-length-constant-time

**Comment by Phhere** [comment]
Since PHP 5.6 there is a function for timing attack safe string comparison so we should use it and add your function as a fallback for older versions

http://php.net/manual/de/function.hash-equals.php

**Comment by JHGitty** [comment]
@Phhere +1 ; great idea!

**Comment by derchrisuk** [comment]
There are also several other implementations on the PHP site.
Just need to find a good overall solution.

**Comment by JHGitty** [comment]
You just need to use the PHP5.6 function and use the above fallback code if the function does not exist for older versions.

**Comment by derchrisuk** [comment]
This is how it is done in the PHP interpreter:

```php
function hash_equals($known_str, $user_str) {
    $result = 0;

    if (!is_string($known_str)) {
        return false;
    }

    if (!is_string($user_str)) {
        return false;
    }

    if (strlen($known_str) != strlen($user_str)) {
        return false;
    }

    for ($j = 0; $j < strlen($known_str); $j++) {
        $result |= ord($known_str[$j]) ^ ord($user_str[$j]);
    }
    return $result === 0;
}
```

**Comment by JHGitty** [comment]
The commit https://github.com/webSPELL/webSPELL/commit/f4513dec8e41aeae04ce25f21bb605bb7af947cd looks great. You can merge it! :+1:
