### ISSUE TITLE
Type-strict password comparison

### ISSUE THREAD

**Issue by Cash2m** [webSPELL/webSPELL#239]
I stumbled across [this topic](https://news.ycombinator.com/item?id=9484757) and noticed the login password check is done with non-strict comparison operator in webSPELL. I did not test if webspell is really affected by this bug/feature/whatever but if *yes* there [might be the chance](https://news.ycombinator.com/item?id=9485146) someone creates an "easy" collision.

Maybe someone can check and tell if this should be changed?

**Comment by Pascalmh** [comment]
We are using sha512 now (https://github.com/webSPELL/webSPELL/commit/e1c0f8094f869211aa55040d84db3a53951a467a) however I think it is a good idea to use strict comparison here (https://github.com/webSPELL/webSPELL/blob/dev/checklogin.php#L74). ref #50

**Comment by derchrisuk** [comment]
See #237

**Comment by Cash2m** [comment]
#237 looks promising. I didn't look for similar issues :no_mouth:

**Comment by JHGitty** [comment]
This issue has been fixed in commit https://github.com/webSPELL/webSPELL/commit/f4513dec8e41aeae04ce25f21bb605bb7af947cd, issue #237.
