### ISSUE TITLE
Login improve UX

### ISSUE THREAD

**Issue by Pascalmh** [webSPELL/webSPELL#241]
- Disable input while login request is loading
- clear and focus password field after failed attempt

**Comment by derchrisuk** [comment]
It could also be the username which is wrong, so focus on password is not a good idea.

**Comment by Pascalmh** [comment]
Handled this here: a07b86962a547029044bbf7f5f32d6bf0fb2c8fc

**Comment by Pascalmh** [comment]
Merged #242
