### ISSUE TITLE
news kommentare

### ISSUE THREAD

**Issue by Talfagoron** [webSPELL/webSPELL#258]
Bei News Schreiben und bearbeiten fehlt Kommentare aktivieren und deaktivieren select.
News Vorschau fehlt bootstrap plugins von den Buttons plus bbcode.html. 
Uploadet von Bildern fehlt languages Banner zu groß und zu klein. 
myprofil fehlt  languages  delete von Avatar userpic löschen (max 90/90) löschen (max 210/210)
Gruß Mokway

**Comment by xxxrenegade** [comment]
Die hier angesprochenen language variablen vom myprofile Module sind in meinem offenen Pull requests gefixt. Aber der wird ja nicht bearbeitet :-(

**Comment by Phhere** [comment]
Nächstes mal bitte einzelne Tickets auf machen. So ist es echt schwer den überblick zu behalten..

**Comment by Phhere** [comment]
Ein paar Fixes dazu sind im [issue-258-Branch](https://github.com/webSPELL/webSPELL/tree/issue-258) zu finden

**Comment by Phhere** [comment]
Der fehlende Languagekey bei myprofile.php ist nun bei Crowdin drin und sollte mit dem nächsten Sync der Sprachen da sein

**Comment by derchrisuk** [comment]
Language Sync wurde letzte Woche durchgeführt.
