### ISSUE TITLE
bug bei forum themen erstellen

### ISSUE THREAD

**Issue by Talfagoron** [webSPELL/webSPELL#259]
Bug bei Themen erstellen beim abspeichern wird Themen nicht gespeichert

**Comment by DDaems** [comment]
Hmm, can you maybe give me a little bit more information on how to reproduce this?
Preferable in english if possible, sinds google translate isn't that accurate. If your not familair with english. Someone else will probably be so kind to translate. :smile: 

Atm, i'm unable to reproduce what your reported.
The only notable little bug i noticed was, that the topic-icon checkbox isn't saved when you selected preview before posting.

Note: i did not have modrewrite enabled while testing, my nginx snippet for rewrite rules is on my desktop enviroment.

**Comment by Pascalmh** [comment]
Reads for me as if a New Topics would not be saved, however - I cannot reproduce it (mod_rewrite is on)
