### ISSUE TITLE
bug bbcode

### ISSUE THREAD

**Issue by Talfagoron** [webSPELL/webSPELL#264]
Notice: Undefined index: na in H:\xampp\htdocs\ws_new\src\func\bbcode.php on line 191

Notice: Undefined index: wrote in H:\xampp\htdocs\ws_new\src\func\bbcode.php on line 431

**Comment by Phhere** [comment]
Where does it happen? Because the language key is available in english language files

**Comment by svnnn** [comment]
https://www.webspell.org/index.php?site=forum_topic&topic=43484

**Comment by xxxrenegade** [comment]
Ich kann den Bug bestätigen, hier wird das ganze noch mal etwas genauer beschreiben.
http://www.webspell.org/index.php?site=forum_topic&topic=43484&type=ASC&page=1

**Comment by Pascalmh** [comment]
Habe das repository gerade nochmal frisch ausgecheckt und kann den fehler nicht reproduzieren, auch auf unserem Staging Server tritt der Fehler nicht auf.

**Comment by xxxrenegade** [comment]
Ich habe webSPELL auf meinem Laptop über XAMPP 5.6.11-0 (PHP Version: 5.6.11) laufen. Und dort tritt der Fehler auch auf. Ich habe es im Admincenter auf Englsh und auf Deutsch getestet und bei beiden Sprachen tritt der Fehler auf. Die Sprachvariablen sind auch in beiden Sprachen vorhanden. Daran liegt es also nicht, es ist auch komisch das der Fehler in der Übersichtsseite ausgegeben wird, wo die Sprachvariablen ja eigentlich gar nicht zum Einsatz kommen.
![clanname - webspell admincenter](https://cloud.githubusercontent.com/assets/2109906/10117197/cab24b98-644e-11e5-8742-ae7bb3af38fa.jpg)

**Comment by svnnn** [comment]
Konnte den Fehler ebenfalls mit PHP 5.6 auf meinem Webspace reproduzieren. Die Funktion "cleartext" in Zeile 581 ist die Ursache für diesen Fehler (http://www.github.com/webSPELL/webSPELL/blob/dev/admin/squads.php#L581).

Kommentiert man folgende beide Zeilen in der Funktion "cleartext" aus, wird kein Fehler ausgegeben: http://github.com/webSPELL/webSPELL/blob/dev/_functions.php#L358-L359. Es muss also an den Funktionen "flags" und "replacement" liegen.

Für die Funktion "flags" habe ich einen entsprechenden Fix, den sich einer der "Profis" mal anschauen sollte:
```
function flags($text, $calledfrom = 'root') {
	global $_language;

	if ($calledfrom == 'admin') {
		$prefix = '../';
		$_language->readModule('bbcode', true, true);
	} else {
		$prefix = '';
		$_language->readModule('bbcode', true, false);
	}
...
```

Für die Funktion "replacement" habe ich allerdings noch keinen Fix gefunden...

**Comment by derchrisuk** [comment]
Ich habe es gerade mal auf unserer Dev Umgebung getestet, da kann ich das auch sehen.
Wir schauen uns das mal genauer an.

**Comment by Pascalmh** [comment]
@svnnn willst du dafür ein Pull Request machen, das sieht korrekt aus!
