### ISSUE TITLE
Font-Awesome integration?

### ISSUE THREAD

**Issue by xxxrenegade** [webSPELL/webSPELL#268]
Wie schaut es eigentlich mit einer http://fortawesome.github.io/Font-Awesome/ integration aus?

Ich baue gerade am Forum module und würde gerne folgende Icons fürs Forum nutzen:
http://fortawesome.github.io/Font-Awesome/icon/file-o/
http://fortawesome.github.io/Font-Awesome/icon/file/
http://fortawesome.github.io/Font-Awesome/icon/file-text-o/
http://fortawesome.github.io/Font-Awesome/icon/file-text/

**Comment by Phhere** [comment]
Da wir Bootstrap nutzen haben wir schon die [Glyphicons] (http://getbootstrap.com/components/#glyphicons) drin

**Comment by xxxrenegade** [comment]
Font-Awesome hat aber eine sehr viel größere Auswahl. Bei den Glyphicons würde man nicht ausreichend verschiedene Icons fürs Forum zusammen bekommen.

**Comment by JHGitty** [comment]
In Bootstrap v4 wird es nach aktueller Lage höchstwahrscheinlich keine Glyphicons mehr geben.
:+1: Bitte zukünftig nur noch FontAwesome nutzen. Die Icons sehen besser aus und werden von vielen Entwicklern gerne verwendet.

**Comment by Pascalmh** [comment]
BS4 bricht dann ohnehin die kompatibilität zu BS3, daher macht es meiner Meinung nach keinen Sinn darüber nun spekulationen anzustellen.

Hatten diese Diskussion Glyphicons vs Font-Awesome auch schon intern und haben uns erstmal gegen FA entschieden da hierdurch noch eine Abhängigkeit mehr entsteht.
