### ISSUE TITLE
Ternäre Operatoren nutzen

### ISSUE THREAD

**Issue by Huskynarr** [webSPELL/webSPELL#269]
Bsp. in der Login.php
```php
if ($anz) { 
    $newmessages = $anz; 
} else { 
    $newmessages = ''; 
}
```
Als Ternärer operator
```php
$newmessages = $anz ? $anz : '';
```
Geht noch hübscher ... aber nur so als Ansatz für die Übersichtlichkeit des Codes. 
;)

**Comment by JHGitty** [comment]
Als Hinweis, sofern ein Neuling hier auftaucht.

Ab PHP7:
``$newmessages = $anz ?? '';``

**Comment by Pascalmh** [comment]
:+1:

**Comment by Phhere** [comment]
Ehrlich gesagt finde ich, dass dieser Code (besonders für unerfahrene Entwickler) schwieriger zu lesen ist. Und es können sich schneller Fehler einschleppen

**Comment by Huskynarr** [comment]
@Phhere  .... guter code oder schludern? Was ist dir lieber?

**Comment by Phhere** [comment]
Was hat das mit gutem Code zu tun?

**Comment by Huskynarr** [comment]
Weil du Anfänger somit raushälst. Die, die wissen wollen was das ist, lernen daran. 
Irgendwo muss man doch anfangen den Code auszumisten.

**Comment by derchrisuk** [comment]
Wir haben das letzte Woche diskutiert, und sehen da zurzeit keinen Handlungsbedarf. Kann sich aber mit einer neueren version auch wieder ändern.
