### ISSUE TITLE
admin/Rubrics  bug 

### ISSUE THREAD

**Issue by nerdiabet** [webSPELL/webSPELL#272]
Ich hab einen kleinen Fehler im Admin Center bei den News Rubriken gefunden.

Und zwar meckert er wegen der variable $tag, dass diese nicht definiert ist. Ändert man bei $File = $tag. $endung; das $Tag zu $id  funktioniert alles wieder richtig

**Comment by Pascalmh** [comment]
@neediabet kannst du dafür einen Pull Request stellen?

**Comment by nerdiabet** [comment]
Wenn ich wüsste, wie das geht. Muss ich dazu einen kostenpflichtigen Account bei Github haben?
Ich habe mich eigentlich nur hier mit angemeldet um dir/euch Fehler zu Webspell zu melden, falls ich welche finde.

**Comment by Pascalmh** [comment]
@nerdiabet nein, du benötigst keinen kostenpflichtigen Account (den brauchst du erst wenn du private repositories haben willst). 

Solche kleine fixes kannst du direkt über github.com machen, dazu einfach die [Datei auswähen](https://github.com/webSPELL/webSPELL/blob/dev/admin/rubrics.php) und auf den Stift zum editieren drücken, und den Anweisungen Folgen.

Sollten nachher größere Sachen hinzukommen müsstest du das Repositroy forken.
Wenn du das nicht möchtest ist das natürlich auch kein Problem, wir sind über die Bug Reports sehr froh und werden sie dann auch selbst fixen - freuen uns natürlich noch mehr über Pull Requests und somit auch neue [Contributor](https://github.com/webSPELL/webSPELL/graphs/contributors).

**Comment by nerdiabet** [comment]
Gut, ist erledigt (:
