### ISSUE TITLE
lang code in index Sprachdatei hinzufügen

### ISSUE THREAD

**Issue by Sysix** [webSPELL/webSPELL#275]
Wichtig für html tag wie z.B. `<html lang="en-US">`
Das es nur ne Auswahl zwischen de, uk, pl, ... gibt kann man als Programmierer nicht genau definieren welche Sprache nun verwendet wird.

Gruß Sysix

**Comment by Pascalmh** [comment]
Das geht schon, wir haben nur keine Übersetzungen die so speziell sind das wir die Region mit angeben müssten/könnten.

>The value [...] identifies the language (in [ISO 639-1](http://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) format) and optionally the region (in [ISO 3166-1 Alpha 2](http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) format) of an alternate URL. For example:
>
>de: German content, independent of region
>en-GB: English content, for GB users
>de-ES: German content, for users in Spain
