### ISSUE TITLE
Run PHP-CS-Fixer

### ISSUE THREAD

**Issue by JHGitty** [webSPELL/webSPELL#282]
I think the developers should run PHP-CS-Fixer to clean up the codestyle of the complete code.
https://github.com/FriendsOfPHP/PHP-CS-Fixer

**Comment by derchrisuk** [comment]
We are already using Codesniffer, and fix non conforming code violations.
So no need for an automatic fixer.

**Comment by JHGitty** [comment]
@derchrisuk I don't know how you can use PHP-CS-Fixer automatically. I only use it manually.

**Comment by derchrisuk** [comment]
We use grunt for deployment. It can be included as a task, but we fix violations manually if any occure.

**Comment by JHGitty** [comment]
@derchrisuk Ok. So I think we can close this issue. Thanks! :-)
