### ISSUE TITLE
Grunt Installation fehlerhaft

### ISSUE THREAD

**Issue by xxxrenegade** [webSPELL/webSPELL#283]
Wenn ich Grunt installieren möchte kommen ganz viele ERR! und WARN Meldungen.

**Comment by Phhere** [comment]
Und welche sind das?
Es ist eigentlich normal, dass einige Warnings und Errors bei Grunt kommen

**Comment by xxxrenegade** [comment]
Es sind aber zimlich viele, wollte erst das log file posten Aber das war extrem groß. Müsste es wen wo hochladen.

**Comment by derchrisuk** [comment]
https://gist.github.com

**Comment by xxxrenegade** [comment]
https://gist.github.com/anonymous/e5024b18647a0ebf6ee4

An sich sollte doch der components Ordner durch Bower angelegt werden.

**Comment by derchrisuk** [comment]
Das Debug log schau ich mir nicht an.
Mich interresiert nur die normale grunt Ausgabe

**Comment by xxxrenegade** [comment]
https://gist.github.com/xxxrenegade/deb910ae5a6ec8c8547f

**Comment by derchrisuk** [comment]
Fehler steht doch da:

`gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.`

**Comment by xxxrenegade** [comment]
OK das Problem habe ich gefixt, aber es läuft immer noch nicht.
https://gist.github.com/xxxrenegade/1057e294ffec65fb4c26

**Comment by derchrisuk** [comment]
Dann wende dich doch mal an den Verursacher der Fehlermeldung.

https://github.com/websockets/bufferutil/issues/27

**Comment by derchrisuk** [comment]
Ich mach das mal hier zu
