### ISSUE TITLE
Use ORM or PDO instead of insecure/outdated commands

### ISSUE THREAD

**Issue by JHGitty** [webSPELL/webSPELL#284]
The developers should use an ORM instead of the outdated/insecure way.

a) http://propelorm.org
b) http://www.doctrine-project.org/projects/orm.html

**Comment by derchrisuk** [comment]
We have no plans to integrate anything like that in the near future.

**Comment by JHGitty** [comment]
@derchrisuk What's about replacing the current mysql functions with PDO?

Pro:
- No security issues in the future (Prepared Statements are stable against SQL Injections, etc.)
- Users can use any DBMS (MySQL, Postgresql, Sqlite, Oracle, etc.)
- The code is more OOP
- It is save for the future (everybody should use PDO on PHP)

If you think it is complicated to change everything to PDO usage you could use it parallel until everything is changed to it.

**Comment by derchrisuk** [comment]
Both PDO and MySQLi support escaping and prepared statements.
And we never had the intention to support another DB then MySQL.
So from this there is no point at the moment to make any changes to the way we speak with the DB.
