### ISSUE TITLE
Password Change Error

### ISSUE THREAD

**Issue by nerdiabet** [webSPELL/webSPELL#286]
I tried to change my password in Webspell 4.3 dev version, and just got the message "ERROR:".
There's no error readable. Debug is ON, error reporting as well.

**Comment by nerdiabet** [comment]
Hab jetzt mal ein wenig Zeit gehabt und nachgeschaut.

Liegt vielleicht daran, dass die Error Variable leer übergeben wird.
&
Es wird überprüft ob der Error string nicht leer ist. Ist das beabsichtigt?
Evtl. würde es funktionieren, wenn man nicht prüft ob die Variable leer ist.

"if (empty($error)) {" Quasi in der Art.

Ich werde es mir zu Hause noch einmal anschauen und sehen, ob sich dadurch wieder alles normalisiert. Aber was mir bis jetzt aufgefallen ist, müsste genau das der Fehler sein.

**Comment by derchrisuk** [comment]
Can reproduce problem on current dev build

**Comment by nerdiabet** [comment]
You tried to Change Your password and it worked? Because i just want to Change it and it Says:" error: "But without a reason. And my thought was that the Problem is probably the if clause where it Checks if there is an error.

**Comment by nerdiabet** [comment]
Fixed it and changed it.
