### ISSUE TITLE
Passwort Sicherheit

### ISSUE THREAD

**Issue by nerdiabet** [webSPELL/webSPELL#293]
Wäre es evtl. eine möglichkeit, dass man von md5 auf eine sichere Verschlüsselung übergeht?
Md5 ist ja mittlerweile geknackt und relativ einfach einen md5 Schlüssel zu lösen.
In der Zeit des fortgeschrittenen Internets wäre es , in meinen Augen, jedenfalls nötig eine neuere und sicherere Verschlüsselung zu wählen. (evt. Sha256) ?

**Comment by derchrisuk** [comment]
Wir nutzen bereits `sha512` fuer die Passwoerter.

**Comment by Huskynarr** [comment]
Jetzt die tolle Frage... Nach welcher Variante?

**Comment by JHGitty** [comment]
https://github.com/webSPELL/webSPELL/blob/3b570f1ffe373edb9ec4015d3108cc201835be59/src/login.php#L43

**Comment by derchrisuk** [comment]
https://github.com/webSPELL/webSPELL/blob/3b570f1ffe373edb9ec4015d3108cc201835be59/src/func/user.php#L351

**Comment by JHGitty** [comment]
Ah, sure, my mistake. The above link from me was for the cookie.

**Comment by nerdiabet** [comment]
Gut, alles klar. Habe ich nicht gesehen.
