### ISSUE TITLE
News Preview

### ISSUE THREAD

**Issue by nerdiabet** [webSPELL/webSPELL#295]
I wanted to post a news and pressed preview.
just came up with this error:
PHP Notice:  Undefined index: window1 in \httpdocs\news.php on line 196
PHP Notice:  Undefined index: window2 in \httpdocs\news.php on line 200
PHP Notice:  Undefined index: window3 in httpdocs\news.php on line 204
PHP Notice:  Undefined index: window4 in httpdocs\news.php on line 208
PHP Notice:  Undefined index: comments in httpdocs\news.php on line 211
PHP Notice:  Undefined variable: languagecount in httpdocs\news.php on line 306

**Comment by derchrisuk** [comment]
There are no errors, just Notices.
And they should be turned off on a production server.

**Comment by nerdiabet** [comment]
Sorry, my fault.
I mean notices.
But still, because of this notices the preview doesnt show up.

**Comment by derchrisuk** [comment]
Just tested, preview is visible.

**Comment by Pascalmh** [comment]
Still should be looked into and fixed before the release. We don't want to have notices be thrown in our code.

**Comment by JHGitty** [comment]
@derchrisuk Notices are bugs. You should not see them on a production server but they are bugs which should be fixed.

**Comment by derchrisuk** [comment]
Notices are NOT bugs.
They are not interrupting the parsing of a PHP script, while an error does.
If they are there or not there doesn't matter for the interpreter.

However they can be annoying if Notices are enabled.

**Comment by JHGitty** [comment]
Notices are kind of bad code / bad practices. So please fix all PHP notices - always!
