### ISSUE TITLE
Feher beim install

### ISSUE THREAD

**Issue by Talfagoron** [webSPELL/webSPELL#297]
Hi habe derzeit fehler beim install komme nur bis step 6 bleibt immer bei 0 % woran liegt den das ??
wollte eben mal was bearbeiten

**Comment by Getschonnik** [comment]
Du hast wo möglich kein Bower benutzt und damit fehlen Dir dann wohl auch die entsprechenden Frameworks (Components).

**Comment by Talfagoron** [comment]
hmm ok was ist den das wieder für ein scheiß ?? gibt es dafür eine Anleitung und was genau soll das sein ??

**Comment by derchrisuk** [comment]
Das ist eine Dev version.
Und hier steht was wie man mit der umgeht

https://github.com/webSPELL/webSPELL/wiki/How-To-Contribute

**Comment by Talfagoron** [comment]
Also komme mit dem install von bower nicht klar jedes mal fehlt irgendwas. gibt es irgendwo eine deutsche Anleitung für Windows 10

**Comment by Getschonnik** [comment]
Probiers mal mit dieser: 

http://getschonnik.de/_issues_ws43/index2.php?issue=bower-install

**Comment by Talfagoron** [comment]
@Getschonnik ,
Danke für deine Anleitung jetzt hat es geklappt
