### ISSUE TITLE
webSPELL 4.3 und XAMPP 5.5.30 (PHP 5.5.30)

### ISSUE THREAD

**Issue by xxxrenegade** [webSPELL/webSPELL#298]
Ich habe zur Zeit folgendes Problem, und zwar bekomme ich webSPELL unter XAMPP 5.5.30 nicht zum laufen bzw. bekomme ich es schon installiert allerdings stimmt da etwas nicht mit den urls diese werden nämlich alle nach folgendem Schema gebildet:
http://127.0.0.1/D:/xampp/htdocs/webSPELL/index.php?site=news

dabei müssten sie natürlich folgendermaßen lauten:
http://127.0.0.1/webSPELL/index.php?site=news

Somit sind sämtliche Verlinkungen nicht korrekt.

**Comment by Getschonnik** [comment]
Würde so grob einfach mal die Hosts Datei (sys..32/Drivers/etc/) mal prüfen ob die 127.0.0.1 direkt in das erst genannte Verzeichnis verweist. 

Wird dir die Seite denn angezeigt?

**Comment by Talfagoron** [comment]
Das ganze habe ich die Woche auch festgestellt bei mir und das design verhauen ist..
hab es jetzt auf mein Server gemacht und bearbeite eben das Admincenter von design

**Comment by xxxrenegade** [comment]
Zur Zeit schaut die hosts-Datei so aus:

# Copyright (c) 1993-2009 Microsoft Corp.
#
# This is a sample HOSTS file used by Microsoft TCP/IP for Windows.
#
# This file contains the mappings of IP addresses to host names. Each
# entry should be kept on an individual line. The IP address should
# be placed in the first column followed by the corresponding host name.
# The IP address and the host name should be separated by at least one
# space.
#
# Additionally, comments (such as these) may be inserted on individual
# lines or following the machine name denoted by a '#' symbol.
#
# For example:
#
#      102.54.94.97     rhino.acme.com          # source server
#       38.25.63.10     x.acme.com              # x client host

# localhost name resolution is handled within DNS itself.
#	127.0.0.1       localhost
#	::1             localhost

**Comment by Getschonnik** [comment]
Die ist leer, also ok. 
Schwierig zu sagen. Hast du nur MySQL und Apache installiert oder das Perl und Co. gedönst mit? 

Optional steht der Pfad auch in x:\xampp\apache\conf\httpd.conf 
Zeile: 244 (DocumentRoot), sollte x:/xampp/htdocs sein .....

**Comment by Pascalmh** [comment]
@Phhere any idea if this might be a bug in the rewrite module?

**Comment by derchrisuk** [comment]
The dev sub is using the same code, working without issues.
Error is more within XAMPP or other local config.

**Comment by xxxrenegade** [comment]
Ich habe das ganze auch mit EasyPHP getestet und dort habe ich das selbe Problem, außerdem hatte wen ich es richtig gesehen auch sQuarg das gleiche Problem auf einem Webserver:
https://www.webspell.org/index.php?site=forum_topic&topic=43559&type=ASC&page=1

**Comment by Getschonnik** [comment]
@xxxrenegade sQuarg sein Problem war, dass Ihm die Komponenten fehlten. Ich habe das webSPELL-Dev für den Upload gepackt und Ihm zur Verfügung gestellt. Das Grafische Problem bei Ihm lag darin, dass der "development" Ordner im Root-Verzeichnis fehlte, damit holte WS die bootstrap.css & Co direkt aus dem components Ordner und nicht aus den darin hinterlegten Framework Ordnern. Soweit läuft es nun also auch bei Ihm und ist fleissig am testen.... trifft das mehr Deinem Problem?

**Comment by Talfagoron** [comment]
Habe den Fehler gefunden bei xamapp in der Datei src/modrewrite.php zeile 104 
in der neuen steht das hier drin
$path = str_replace(realpath($_SERVER['DOCUMENT_ROOT']), '', dirname($_SERVER['SCRIPT_FILENAME']));

in der alten das hier 

$path = str_replace(realpath($_SERVER['DOCUMENT_ROOT']), '', realpath(dirname(__FILE__) . '/../'));

mit der alten Version läuft es mit der neuen nicht

**Comment by xxxrenegade** [comment]
Das ganze muss eigentlich an der src/modrewrite.php liegen dort wird ja die url für des Base Tag gebildet.

<base href="/D:/Program Files (x86)/EasyPHP-DevServer-14.1VC11/data/localweb/webSPELL/">

**Comment by nerdiabet** [comment]
Kann das Selbe Problem auch grade wieder reproduzieren. Apache mit PHP7 & direkt auf dem Webserver meines Anbieters. Frischer Install und die Seite kann keine Stylesheets noch sonst irgend etwas laden, da die Mod Rewrite alles falsch ausliest.

**Comment by xxxrenegade** [comment]
Unter XAMPP 7.0.5 (PHP 7.0.5) läuft es mit beiden Varianten nicht mehr!
