### ISSUE TITLE
(admin) sending a newsletter ending with a fatal error

### ISSUE THREAD

**Issue by blu3bird23** [webSPELL/webSPELL#302]
Fatal error: Uncaught exception 'UnexpectedValueException' with message 'DirectoryIterator::__construct(languages/): failed to open dir: No such file or directory' in /var/customers/webs/xxx/subs/webspell/src/func/language.php:43 Stack trace: #0 /var/customers/webs/xxx/subs/webspell/src/func/language.php(43): DirectoryIterator->__construct('languages/') #1 /var/customers/webs/xxx/subs/webspell/admin/newsletter.php(48): webspell\Language->setLanguage('en') #2 /var/customers/webs/xxx/subs/webspell/admin/admincenter.php(248): include('/var/customers/...') #3 {main} thrown in /var/customers/webs/xxxx/subs/webspell/src/func/language.php on line 43

**Comment by derchrisuk** [comment]
Should be fixed with 205861abe1de9ecf1fdbe1349d2c2af6f0b8cd65

**Comment by blu3bird23** [comment]
it works but:

Warning: file_exists(): open_basedir restriction in effect. File(../../languages/en/admin/newsletter.php) is not within the allowed path(s):

i dont know why he tries to use ../../ instead of ../language/

**Comment by Getschonnik** [comment]
Das Problem ist das module(), dort ist ebenfalls die Prüfung ob admin und setzt ein (../) vor dem Pfad. 
Es muss also nach Beendigung der direkte Pfad wieder zurückgegeben werden, damit das Modul den korrekten Pfad angibt erhält. 

Nach Zeile 45: ( $this->language = $to;)
$this->language_path = 'languages/';

**Comment by Getschonnik** [comment]
Das Problem ist das module(), dort ist ebenfalls die Prüfung ob admin und setzt ein (../) vor dem Pfad. 
Es muss also nach Beendigung der direkte Pfad wieder zurückgegeben werden, damit das Modul den korrekten Pfad angibt erhält.

src/func/language.php - nach Zeile 45: 
$this->language_path = 'languages/';

**Comment by derchrisuk** [comment]
Fixed with #304
