### ISSUE TITLE
(demos) adding a demo ends with a fatal error

### ISSUE THREAD

**Issue by blu3bird23** [webSPELL/webSPELL#303]
Fatal error: Cannot use object of type webspell\HttpUpload as array in /var/customers/webs/xxxx/subs/webspell/demos.php on line 75

And why is "External link" a required field?
Either I upload a file up, or use an external link.

PHP-Version: 5.6.17-1~dotdeb+7.1

**Comment by Getschonnik** [comment]
75:[ - ]    #$file = $demo[ 'name' ];
                 76:[ + ]   $file = $demo->getFileName();

**Comment by Pascalmh** [comment]
@Getschonnik can you open a Pull Request for that one?
