### ISSUE TITLE
Components Ordner fehlt im Dev Branch

### ISSUE THREAD

**Issue by SlicewOw** [webSPELL/webSPELL#316]
Bei der Installation ist mir aufgefallen, dass der Ordner komplett fehlt - Absicht?

Geht um den gesamten Ordner `components` im Branch `dev`.

**Comment by xxxrenegade** [comment]
Es ist beabsichtigt, du solltest dir mal den [How to contribute](https://github.com/webSPELL/webSPELL/wiki/How-To-Contribute) Artikel angucken. Der Ordner wird mit bower angelegt.
