### ISSUE TITLE
Clanwars-News comments appear under clanwars 

### ISSUE THREAD

**Issue by Pascalmh** [webSPELL/webSPELL#59]
Clanwar News appear underneath the clanwars and not underneath the news

Original Message from Mokway:
>Hi wollte nur mal Bescheid geben das es bei der news.php in Bug gibt wenn du ein
Clanwar in den News veröffentlicht Un ein User ein Kommentar schreibt zeigt er nicht bei den News an sondern unter clanwars sollte mal behoben werden

**Comment by Phhere** [comment]
Seit 040748adb324cd92ed98b42683e3cec861780211 werden nun bei Clanwar News unter der News die Kommentare zum Clanwar angezeigt
