### ISSUE TITLE
Make Regex for copyright replace work for Links

### ISSUE THREAD

**Issue by Pascalmh** [webSPELL/webSPELL#95]
Run `grunt replace:copyright` - you will see that the imprint.html will get updated and the link to webspell.org will be destroyed.

**Comment by Pascalmh** [comment]
https://github.com/webSPELL/webSPELL-4.2.3/blob/dev/admin/admincenter.php#L263

**Comment by derchrisuk** [comment]
Rather then tweaking the regex for the admincenter, I would modify the copyright to match with all the other files.

**Comment by Pascalmh** [comment]
:+1:
